export * from './assignmentController.service';
import { AssignmentControllerService } from './assignmentController.service';
export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './courseController.service';
import { CourseControllerService } from './courseController.service';
export * from './courseEnrollmentController.service';
import { CourseEnrollmentControllerService } from './courseEnrollmentController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AssignmentControllerService, AuthenticationControllerService, BasicErrorControllerService, CourseControllerService, CourseEnrollmentControllerService, UserControllerService];
